import axios from 'axios';
import Head from 'next/head';
import { InferGetStaticPropsType } from 'next';
import { T01Blocks } from '../components/templates/T01Blocks/T01Blocks';
import { S01Header } from '../components/blocks/S01Header/S01Header';
import { Container, DesktopPadding, Wrapper } from '../styles/layout';
import { S03ProfileCard } from '../components/blocks/S03ProfileCard/S03ProfileCard';
import { S05SideNavigation } from '../components/blocks/S05SideNavigation/S05SideNavigation';
import { BackgroundShapes } from '../components/atoms/BackgroundShapes/BackgroundShapes';

const Home = ({
  logo,
  blocks,
  profile,
  social,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log('profile', profile);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundShapes />

      <S01Header logo={logo} />

      <main>
        <DesktopPadding>
          <Container>
            <Wrapper>
              <S05SideNavigation />
              <S03ProfileCard data={profile} social={social} />
              <T01Blocks blocks={blocks} />
            </Wrapper>
          </Container>
        </DesktopPadding>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const HEADER_PATH = 's01-header?populate=*';
  const PROFILE_PATH = 's03-profile-card?populate=*';
  const SOCIAL_PATH = 's04-social-sharing?populate=*';
  const BLOCKS_PATH = 'blocks?populate[Components][populate]=*';

  const blocksData = await axios.get(`${process.env.API_HOST}${BLOCKS_PATH}`).catch(() => {});
  const headerData = await axios.get(`${process.env.API_HOST}${HEADER_PATH}`).catch(() => {});
  const profileData = await axios.get(`${process.env.API_HOST}${PROFILE_PATH}`).catch(() => {});
  const socialData = await axios.get(`${process.env.API_HOST}${SOCIAL_PATH}`).catch(() => {});

  const logo = (headerData || {}).data.data.attributes.Logo.data.attributes || null;
  const blocks = (blocksData || {}).data || null;
  const profile = (profileData || {}).data || null;
  const social = (socialData || {}).data || null;

  return {
    props: {
      blocks,
      logo,
      profile,
      social,
    },
  };
};

export default Home;
