import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import * as S from './index.styles';

const Home: NextPage = () => {
  return (
    <S.StyledHome>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.StyledHeader>header</S.StyledHeader>

      <S.StyledMain>main</S.StyledMain>

      <S.StyledFooter>footer</S.StyledFooter>
    </S.StyledHome>
  );
};

export default Home;
